#ifndef STATION_HW_PIN_MAP_H
#define STATION_HW_PIN_MAP_H

#ifdef __cplusplus
extern "C" {
#endif

// ---- hardware pins mapping to application domain ----
// Sensor Pin Assignments
#define HW_SOIL_MOISTURE_PIN    GPIO_PIN_6 // PA6
#define HW_SOIL_MOISTURE_ADC_CH ADC_CHANNEL_6

#define HW_LIGHT_SENSOR_CH1_PIN GPIO_PIN_7 // PA7
#define HW_LIGHT_SENSOR_CH2_PIN GPIO_PIN_1 // PB1
#define HW_LIGHT_SENSOR_ADC_CH1 ADC_CHANNEL_7
#define HW_LIGHT_SENSOR_ADC_CH2 ADC_CHANNEL_9

#define HW_AIRTEMP_PORT GPIOB
#define HW_AIRTEMP_PIN  GPIO_PIN_8

// Actuator Pin Assignments
#define HW_PUMP_PORT GPIOC
#define HW_PUMP_PIN  GPIO_PIN_13

#define HW_FAN_PORT GPIOC
#define HW_FAN_PIN  GPIO_PIN_1

#define HW_BULB_PORT GPIOC
#define HW_BULB_PIN  GPIO_PIN_0

// Display Pin Assignments
#define HW_DISPLAY_RST_PORT      GPIOB
#define HW_DISPLAY_RST_PIN       GPIO_PIN_14
#define HW_DISPLAY_DC_PORT       GPIOB
#define HW_DISPLAY_DC_PIN        GPIO_PIN_15
#define HW_DISPLAY_SPI_SCK_PORT  GPIOB
#define HW_DISPLAY_SPI_SCK_PIN   GPIO_PIN_13
#define HW_DISPLAY_SPI_SCK_AF    GPIO_AF5_SPI2
#define HW_DISPLAY_SPI_MOSI_PORT GPIOC
#define HW_DISPLAY_SPI_MOSI_PIN  GPIO_PIN_3
#define HW_DISPLAY_SPI_MOSI_AF   GPIO_AF5_SPI2

// Network Device (ESP8266) Pin Assignments
#define HW_ESP8266_UART_RX_PORT GPIOC
#define HW_ESP8266_UART_RX_PIN  GPIO_PIN_5
#define HW_ESP8266_UART_RX_AF   GPIO_AF7_USART3
#define HW_ESP8266_UART_TX_PORT GPIOB
#define HW_ESP8266_UART_TX_PIN  GPIO_PIN_10
#define HW_ESP8266_UART_TX_AF   GPIO_AF7_USART3
#define HW_ESP8266_RST_PORT     ESP8266_RST_PINGRP
#define HW_ESP8266_RST_PIN      ESP8266_RST_PINNUM

// Entropy Source (HCSR04) Pin Assignments
#define HW_ENTROPY_TRIG_PORT ENTROPY_HCSR04_OUT_GRP
#define HW_ENTROPY_TRIG_PIN  ENTROPY_HCSR04_OUT_PINNUM
#define HW_ENTROPY_ECHO_PORT ENTROPY_HCSR04_IN_GRP
#define HW_ENTROPY_ECHO_PIN  ENTROPY_HCSR04_IN_PINNUM

#ifdef __cplusplus
}
#endif
#endif // end of STATION_HW_PIN_MAP_H
